/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package HelloWorldNode40

import HelloWorldNode40.resources.HelloWorldDropwizardResource
import io.dropwizard.testing.junit.ResourceTestRule
import org.junit.Rule
import spock.lang.Specification

import static javax.ws.rs.core.MediaType.APPLICATION_JSON_TYPE

class AppTest extends Specification {
    @Rule
    ResourceTestRule resources = ResourceTestRule.builder()
            .addResource(new HelloWorldDropwizardResource())
            .build()
    def "simpleHello"() {

        when: "curl endpoint is hit"
        String result = HelloWorldDropwizardResource
                .("/hello-world")
                .request(APPLICATION_JSON_TYPE)

        then:
        result == "Hello! How are you today?"

    }
}

